import type {ITrack, ITrackPosition} from "./track";
import type {IArtist} from "./artist";
import type {ILabel, IPager} from "./infoModels";
import type {ICustomWave} from "./wave";

export interface IAlbum {
    id: number,
    error?: String,
    title?: String,
    track_count?: number,
    artists: IArtist[],
    labels: ILabel[],
    available?: boolean,
    available_for_premium_users?: boolean,
    version?: String,
    cover_uri?: String,
    content_warning?: String,
    genre?: String,
    text_color?: String,
    short_description?: String,
    description?: String,
    is_premiere?: boolean,
    is_banner?: boolean,
    meta_type?: String,
    storage_dir?: String,
    og_image?: String,
    recent?: boolean,
    very_important?: boolean,
    available_for_mobile?: boolean,
    available_partially?: boolean,
    bests: number[],
    duplicates: IAlbum[],
    volumes: ITrack[],
    year?: number,
    release_date?: String,
    item_type?: String,
    track_position?: ITrackPosition,
    regions: String[],
    available_as_rbt?: boolean,
    lyrics_available?: boolean,
    remember_position?: boolean,
    albums: IAlbum[],
    duration_ms?: number,
    explicit?: boolean,
    start_date?: String,
    likes_count?: number,
    available_regions: String[],
    available_for_options: String[],
    meta_tag_id?: String,
    has_trailer?: boolean,
    sort_order?: String,
    background_image_url?: String,
    custom_wave?: ICustomWave,
    pager?: IPager,
}

